### ISSUE TITLE
Ability to handle "features.tsv" aswell as "genes.tsv" 

### ISSUE THREAD

**Issue by fnaji** [tercen/read_cellranger_operator#2]
In the cellranger upload zip file, there are three key files
barcodes.tsv, genes.tsv, matrix.mtx 

Sometimes, the genes.tsv file is called features.tsv.

It would be great if this operator handled this as well.

**Comment by fnaji** [comment]
This is the error message that is generated:
`Failed to run operator, exit code = 1 --ERR-- WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. Error in Seurat::Read10X(data.dir = x) : Directory provided does not exist Calls: lapply -> FUN ->`

Great if the operator could give a better error message in the case where it does not find the barcodes, genes, and matrix files.

**Comment by makostadima** [comment]
@fnaji the operator seems to be able to handle files called 'features.csv'. Look at the following lines of code:

https://github.com/tercen/read_cellranger_operator/blob/master/main.R#L24-L27

I think the best approach here to understand what the problem is is to get the original dataset from Sneha. I will be doing that and let you know once I figure out wht the source of the error was.

**Comment by makostadima** [comment]
Here's the dataset that causes the issue: https://drive.google.com/file/d/10ODBepw6iJf9P-_4lsyx-XDoxJI5lkR8/view?usp=sharing

**Comment by makostadima** [comment]
So there are mutliple issues with this dataset as is:
- Seurat::Read10X() expects a directory as an input. 
- This directory should contain files that don't have any prefix. The function itself expects to find the following files: barcodes.tsv, genes.tsv OR features.tsv.gz and matrix.mtx". And this behaviour can't be modified.

As long as we make this clear in the README file I believe that there's nothing else to be done in this case.
